// Generated by gencpp from file cam/goal.msg
// DO NOT EDIT!


#ifndef CAM_MESSAGE_GOAL_H
#define CAM_MESSAGE_GOAL_H

#include <ros/service_traits.h>


#include <cam/goalRequest.h>
#include <cam/goalResponse.h>


namespace cam
{

struct goal
{

typedef goalRequest Request;
typedef goalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct goal
} // namespace cam


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cam::goal > {
  static const char* value()
  {
    return "2ceead7433605f9dde8aff8b1e4a54fc";
  }

  static const char* value(const ::cam::goal&) { return value(); }
};

template<>
struct DataType< ::cam::goal > {
  static const char* value()
  {
    return "cam/goal";
  }

  static const char* value(const ::cam::goal&) { return value(); }
};


// service_traits::MD5Sum< ::cam::goalRequest> should match
// service_traits::MD5Sum< ::cam::goal >
template<>
struct MD5Sum< ::cam::goalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cam::goal >::value();
  }
  static const char* value(const ::cam::goalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cam::goalRequest> should match
// service_traits::DataType< ::cam::goal >
template<>
struct DataType< ::cam::goalRequest>
{
  static const char* value()
  {
    return DataType< ::cam::goal >::value();
  }
  static const char* value(const ::cam::goalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cam::goalResponse> should match
// service_traits::MD5Sum< ::cam::goal >
template<>
struct MD5Sum< ::cam::goalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cam::goal >::value();
  }
  static const char* value(const ::cam::goalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cam::goalResponse> should match
// service_traits::DataType< ::cam::goal >
template<>
struct DataType< ::cam::goalResponse>
{
  static const char* value()
  {
    return DataType< ::cam::goal >::value();
  }
  static const char* value(const ::cam::goalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAM_MESSAGE_GOAL_H
