// Generated by gencpp from file cam/num_stateRequest.msg
// DO NOT EDIT!


#ifndef CAM_MESSAGE_NUM_STATEREQUEST_H
#define CAM_MESSAGE_NUM_STATEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cam
{
template <class ContainerAllocator>
struct num_stateRequest_
{
  typedef num_stateRequest_<ContainerAllocator> Type;

  num_stateRequest_()
    : num_state()  {
    }
  num_stateRequest_(const ContainerAllocator& _alloc)
    : num_state(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _num_state_type;
  _num_state_type num_state;





  typedef boost::shared_ptr< ::cam::num_stateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cam::num_stateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct num_stateRequest_

typedef ::cam::num_stateRequest_<std::allocator<void> > num_stateRequest;

typedef boost::shared_ptr< ::cam::num_stateRequest > num_stateRequestPtr;
typedef boost::shared_ptr< ::cam::num_stateRequest const> num_stateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cam::num_stateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cam::num_stateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cam::num_stateRequest_<ContainerAllocator1> & lhs, const ::cam::num_stateRequest_<ContainerAllocator2> & rhs)
{
  return lhs.num_state == rhs.num_state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cam::num_stateRequest_<ContainerAllocator1> & lhs, const ::cam::num_stateRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cam

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::cam::num_stateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cam::num_stateRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cam::num_stateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cam::num_stateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cam::num_stateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cam::num_stateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cam::num_stateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c16ab6459bae9937022fc76d8c8e3999";
  }

  static const char* value(const ::cam::num_stateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc16ab6459bae9937ULL;
  static const uint64_t static_value2 = 0x022fc76d8c8e3999ULL;
};

template<class ContainerAllocator>
struct DataType< ::cam::num_stateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cam/num_stateRequest";
  }

  static const char* value(const ::cam::num_stateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cam::num_stateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[] num_state\n"
;
  }

  static const char* value(const ::cam::num_stateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cam::num_stateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.num_state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct num_stateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cam::num_stateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cam::num_stateRequest_<ContainerAllocator>& v)
  {
    s << indent << "num_state[]" << std::endl;
    for (size_t i = 0; i < v.num_state.size(); ++i)
    {
      s << indent << "  num_state[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.num_state[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAM_MESSAGE_NUM_STATEREQUEST_H
