// Generated by gencpp from file cam/num_state.msg
// DO NOT EDIT!


#ifndef CAM_MESSAGE_NUM_STATE_H
#define CAM_MESSAGE_NUM_STATE_H

#include <ros/service_traits.h>


#include <cam/num_stateRequest.h>
#include <cam/num_stateResponse.h>


namespace cam
{

struct num_state
{

typedef num_stateRequest Request;
typedef num_stateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct num_state
} // namespace cam


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cam::num_state > {
  static const char* value()
  {
    return "3ef8d46e3fcd35484b18eba316522655";
  }

  static const char* value(const ::cam::num_state&) { return value(); }
};

template<>
struct DataType< ::cam::num_state > {
  static const char* value()
  {
    return "cam/num_state";
  }

  static const char* value(const ::cam::num_state&) { return value(); }
};


// service_traits::MD5Sum< ::cam::num_stateRequest> should match
// service_traits::MD5Sum< ::cam::num_state >
template<>
struct MD5Sum< ::cam::num_stateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cam::num_state >::value();
  }
  static const char* value(const ::cam::num_stateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cam::num_stateRequest> should match
// service_traits::DataType< ::cam::num_state >
template<>
struct DataType< ::cam::num_stateRequest>
{
  static const char* value()
  {
    return DataType< ::cam::num_state >::value();
  }
  static const char* value(const ::cam::num_stateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cam::num_stateResponse> should match
// service_traits::MD5Sum< ::cam::num_state >
template<>
struct MD5Sum< ::cam::num_stateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cam::num_state >::value();
  }
  static const char* value(const ::cam::num_stateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cam::num_stateResponse> should match
// service_traits::DataType< ::cam::num_state >
template<>
struct DataType< ::cam::num_stateResponse>
{
  static const char* value()
  {
    return DataType< ::cam::num_state >::value();
  }
  static const char* value(const ::cam::num_stateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAM_MESSAGE_NUM_STATE_H
