// Generated by gencpp from file cam/UIntArray.msg
// DO NOT EDIT!


#ifndef CAM_MESSAGE_UINTARRAY_H
#define CAM_MESSAGE_UINTARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cam
{
template <class ContainerAllocator>
struct UIntArray_
{
  typedef UIntArray_<ContainerAllocator> Type;

  UIntArray_()
    : time_stamp(0.0)
    , data()  {
    }
  UIntArray_(const ContainerAllocator& _alloc)
    : time_stamp(0.0)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef double _time_stamp_type;
  _time_stamp_type time_stamp;

   typedef std::vector<uint64_t, typename ContainerAllocator::template rebind<uint64_t>::other >  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::cam::UIntArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cam::UIntArray_<ContainerAllocator> const> ConstPtr;

}; // struct UIntArray_

typedef ::cam::UIntArray_<std::allocator<void> > UIntArray;

typedef boost::shared_ptr< ::cam::UIntArray > UIntArrayPtr;
typedef boost::shared_ptr< ::cam::UIntArray const> UIntArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cam::UIntArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cam::UIntArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cam::UIntArray_<ContainerAllocator1> & lhs, const ::cam::UIntArray_<ContainerAllocator2> & rhs)
{
  return lhs.time_stamp == rhs.time_stamp &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cam::UIntArray_<ContainerAllocator1> & lhs, const ::cam::UIntArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cam

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::cam::UIntArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cam::UIntArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cam::UIntArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cam::UIntArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cam::UIntArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cam::UIntArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cam::UIntArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d2631c5713f06405dcb0ef2b331886d9";
  }

  static const char* value(const ::cam::UIntArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd2631c5713f06405ULL;
  static const uint64_t static_value2 = 0xdcb0ef2b331886d9ULL;
};

template<class ContainerAllocator>
struct DataType< ::cam::UIntArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cam/UIntArray";
  }

  static const char* value(const ::cam::UIntArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cam::UIntArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 time_stamp\n"
"uint64[] data\n"
"\n"
"\n"
"\n"
"\n"
;
  }

  static const char* value(const ::cam::UIntArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cam::UIntArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.time_stamp);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UIntArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cam::UIntArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cam::UIntArray_<ContainerAllocator>& v)
  {
    s << indent << "time_stamp: ";
    Printer<double>::stream(s, indent + "  ", v.time_stamp);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<uint64_t>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAM_MESSAGE_UINTARRAY_H
