// Generated by gencpp from file beacon_cam/cup_camera.msg
// DO NOT EDIT!


#ifndef BEACON_CAM_MESSAGE_CUP_CAMERA_H
#define BEACON_CAM_MESSAGE_CUP_CAMERA_H

#include <ros/service_traits.h>


#include <beacon_cam/cup_cameraRequest.h>
#include <beacon_cam/cup_cameraResponse.h>


namespace beacon_cam
{

struct cup_camera
{

typedef cup_cameraRequest Request;
typedef cup_cameraResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct cup_camera
} // namespace beacon_cam


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::beacon_cam::cup_camera > {
  static const char* value()
  {
    return "7a20991e451c1198c7723ab0b4776fd9";
  }

  static const char* value(const ::beacon_cam::cup_camera&) { return value(); }
};

template<>
struct DataType< ::beacon_cam::cup_camera > {
  static const char* value()
  {
    return "beacon_cam/cup_camera";
  }

  static const char* value(const ::beacon_cam::cup_camera&) { return value(); }
};


// service_traits::MD5Sum< ::beacon_cam::cup_cameraRequest> should match
// service_traits::MD5Sum< ::beacon_cam::cup_camera >
template<>
struct MD5Sum< ::beacon_cam::cup_cameraRequest>
{
  static const char* value()
  {
    return MD5Sum< ::beacon_cam::cup_camera >::value();
  }
  static const char* value(const ::beacon_cam::cup_cameraRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::beacon_cam::cup_cameraRequest> should match
// service_traits::DataType< ::beacon_cam::cup_camera >
template<>
struct DataType< ::beacon_cam::cup_cameraRequest>
{
  static const char* value()
  {
    return DataType< ::beacon_cam::cup_camera >::value();
  }
  static const char* value(const ::beacon_cam::cup_cameraRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::beacon_cam::cup_cameraResponse> should match
// service_traits::MD5Sum< ::beacon_cam::cup_camera >
template<>
struct MD5Sum< ::beacon_cam::cup_cameraResponse>
{
  static const char* value()
  {
    return MD5Sum< ::beacon_cam::cup_camera >::value();
  }
  static const char* value(const ::beacon_cam::cup_cameraResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::beacon_cam::cup_cameraResponse> should match
// service_traits::DataType< ::beacon_cam::cup_camera >
template<>
struct DataType< ::beacon_cam::cup_cameraResponse>
{
  static const char* value()
  {
    return DataType< ::beacon_cam::cup_camera >::value();
  }
  static const char* value(const ::beacon_cam::cup_cameraResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BEACON_CAM_MESSAGE_CUP_CAMERA_H
