// Generated by gencpp from file beacon_cam/point_transformResponse.msg
// DO NOT EDIT!


#ifndef BEACON_CAM_MESSAGE_POINT_TRANSFORMRESPONSE_H
#define BEACON_CAM_MESSAGE_POINT_TRANSFORMRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beacon_cam
{
template <class ContainerAllocator>
struct point_transformResponse_
{
  typedef point_transformResponse_<ContainerAllocator> Type;

  point_transformResponse_()
    : tf_pos()  {
    }
  point_transformResponse_(const ContainerAllocator& _alloc)
    : tf_pos(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _tf_pos_type;
  _tf_pos_type tf_pos;





  typedef boost::shared_ptr< ::beacon_cam::point_transformResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beacon_cam::point_transformResponse_<ContainerAllocator> const> ConstPtr;

}; // struct point_transformResponse_

typedef ::beacon_cam::point_transformResponse_<std::allocator<void> > point_transformResponse;

typedef boost::shared_ptr< ::beacon_cam::point_transformResponse > point_transformResponsePtr;
typedef boost::shared_ptr< ::beacon_cam::point_transformResponse const> point_transformResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beacon_cam::point_transformResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beacon_cam::point_transformResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::beacon_cam::point_transformResponse_<ContainerAllocator1> & lhs, const ::beacon_cam::point_transformResponse_<ContainerAllocator2> & rhs)
{
  return lhs.tf_pos == rhs.tf_pos;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::beacon_cam::point_transformResponse_<ContainerAllocator1> & lhs, const ::beacon_cam::point_transformResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace beacon_cam

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::beacon_cam::point_transformResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beacon_cam::point_transformResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beacon_cam::point_transformResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beacon_cam::point_transformResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beacon_cam::point_transformResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beacon_cam::point_transformResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beacon_cam::point_transformResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ae905da94d0aa87c4e9cf6404d56be17";
  }

  static const char* value(const ::beacon_cam::point_transformResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xae905da94d0aa87cULL;
  static const uint64_t static_value2 = 0x4e9cf6404d56be17ULL;
};

template<class ContainerAllocator>
struct DataType< ::beacon_cam::point_transformResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beacon_cam/point_transformResponse";
  }

  static const char* value(const ::beacon_cam::point_transformResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beacon_cam::point_transformResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] tf_pos\n"
"\n"
"\n"
"\n"
;
  }

  static const char* value(const ::beacon_cam::point_transformResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beacon_cam::point_transformResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.tf_pos);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct point_transformResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beacon_cam::point_transformResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beacon_cam::point_transformResponse_<ContainerAllocator>& v)
  {
    s << indent << "tf_pos[]" << std::endl;
    for (size_t i = 0; i < v.tf_pos.size(); ++i)
    {
      s << indent << "  tf_pos[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.tf_pos[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEACON_CAM_MESSAGE_POINT_TRANSFORMRESPONSE_H
