// Generated by gencpp from file algo/stringArray.msg
// DO NOT EDIT!


#ifndef ALGO_MESSAGE_STRINGARRAY_H
#define ALGO_MESSAGE_STRINGARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace algo
{
template <class ContainerAllocator>
struct stringArray_
{
  typedef stringArray_<ContainerAllocator> Type;

  stringArray_()
    : time_stamp(0.0)
    , data()  {
    }
  stringArray_(const ContainerAllocator& _alloc)
    : time_stamp(0.0)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef double _time_stamp_type;
  _time_stamp_type time_stamp;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::algo::stringArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::algo::stringArray_<ContainerAllocator> const> ConstPtr;

}; // struct stringArray_

typedef ::algo::stringArray_<std::allocator<void> > stringArray;

typedef boost::shared_ptr< ::algo::stringArray > stringArrayPtr;
typedef boost::shared_ptr< ::algo::stringArray const> stringArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::algo::stringArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::algo::stringArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::algo::stringArray_<ContainerAllocator1> & lhs, const ::algo::stringArray_<ContainerAllocator2> & rhs)
{
  return lhs.time_stamp == rhs.time_stamp &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::algo::stringArray_<ContainerAllocator1> & lhs, const ::algo::stringArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace algo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::algo::stringArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::algo::stringArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::algo::stringArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::algo::stringArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::algo::stringArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::algo::stringArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::algo::stringArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "93db99df41c7f7b2322d7c908b9a2274";
  }

  static const char* value(const ::algo::stringArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x93db99df41c7f7b2ULL;
  static const uint64_t static_value2 = 0x322d7c908b9a2274ULL;
};

template<class ContainerAllocator>
struct DataType< ::algo::stringArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "algo/stringArray";
  }

  static const char* value(const ::algo::stringArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::algo::stringArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 time_stamp\n"
"string[] data\n"
"\n"
"\n"
"\n"
"\n"
;
  }

  static const char* value(const ::algo::stringArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::algo::stringArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.time_stamp);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct stringArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::algo::stringArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::algo::stringArray_<ContainerAllocator>& v)
  {
    s << indent << "time_stamp: ";
    Printer<double>::stream(s, indent + "  ", v.time_stamp);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ALGO_MESSAGE_STRINGARRAY_H
