// Generated by gencpp from file core/route_command.msg
// DO NOT EDIT!


#ifndef CORE_MESSAGE_ROUTE_COMMAND_H
#define CORE_MESSAGE_ROUTE_COMMAND_H

#include <ros/service_traits.h>


#include <core/route_commandRequest.h>
#include <core/route_commandResponse.h>


namespace core
{

struct route_command
{

typedef route_commandRequest Request;
typedef route_commandResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct route_command
} // namespace core


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::core::route_command > {
  static const char* value()
  {
    return "e934608428f4a678bcc6b43ef7249b80";
  }

  static const char* value(const ::core::route_command&) { return value(); }
};

template<>
struct DataType< ::core::route_command > {
  static const char* value()
  {
    return "core/route_command";
  }

  static const char* value(const ::core::route_command&) { return value(); }
};


// service_traits::MD5Sum< ::core::route_commandRequest> should match
// service_traits::MD5Sum< ::core::route_command >
template<>
struct MD5Sum< ::core::route_commandRequest>
{
  static const char* value()
  {
    return MD5Sum< ::core::route_command >::value();
  }
  static const char* value(const ::core::route_commandRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::core::route_commandRequest> should match
// service_traits::DataType< ::core::route_command >
template<>
struct DataType< ::core::route_commandRequest>
{
  static const char* value()
  {
    return DataType< ::core::route_command >::value();
  }
  static const char* value(const ::core::route_commandRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::core::route_commandResponse> should match
// service_traits::MD5Sum< ::core::route_command >
template<>
struct MD5Sum< ::core::route_commandResponse>
{
  static const char* value()
  {
    return MD5Sum< ::core::route_command >::value();
  }
  static const char* value(const ::core::route_commandResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::core::route_commandResponse> should match
// service_traits::DataType< ::core::route_command >
template<>
struct DataType< ::core::route_commandResponse>
{
  static const char* value()
  {
    return DataType< ::core::route_command >::value();
  }
  static const char* value(const ::core::route_commandResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CORE_MESSAGE_ROUTE_COMMAND_H
