(cl:defpackage beacon_cam-srv
  (:use )
  (:export
   "CUP_CAMERA"
   "<CUP_CAMERA-REQUEST>"
   "CUP_CAMERA-REQUEST"
   "<CUP_CAMERA-RESPONSE>"
   "CUP_CAMERA-RESPONSE"
   "POINT_TRANSFORM"
   "<POINT_TRANSFORM-REQUEST>"
   "POINT_TRANSFORM-REQUEST"
   "<POINT_TRANSFORM-RESPONSE>"
   "POINT_TRANSFORM-RESPONSE"
  ))

